In [1]:
import numpy as np

def create_array(shape, elements):
    array = np.array(elements).reshape(shape)
    print(f"Array created successfully:\n{array}")
    return array

def indexing(array, row, col, depth=None):
    if depth is None:
        return array[row, col]
    else:
        return array[depth, row, col]

def slicing(array, row_range, col_range, depth_range=None):
    if depth_range is None:
        return array[row_range[0]:row_range[1], col_range[0]:col_range[1]]
    else:
        return array[depth_range[0]:depth_range[1], row_range[0]:row_range[1], col_range[0]:col_range[1]]

def math_operations(array, other_array, operation):
    match operation:
        case 1:  # Addition
            return np.add(array, other_array)
        case 2:  # Subtraction
            return np.subtract(array, other_array)
        case 3:  # Multiplication
            return np.multiply(array, other_array)
        case 4:  # Division
            return np.divide(array, other_array)

def combine_arrays(array, other_array):
    return np.vstack((array, other_array))

def split_array(array, num_splits):
    return np.array_split(array, num_splits)

def search_value(array, value):
    return np.where(array == value)

def sort_array(array):
    return np.sort(array, axis=1)

def filter_array(array, condition):
    return array[array > condition]

def sum(array):
    return np.sum(array)

def mean(array):
    return np.mean(array)

def median(array):
    return np.median(array)

def std_dev(array):
    return np.std(array)

def variance(array):
    return np.var(array)

def print_welcome():
    print("Welcome to the NumPy Analyzer!")

def print_exit_message():
    print("Thank you for using the NumPy Analyzer! Goodbye!")

def main():
    array = None

    print_welcome()

    while True:
        print("\nChoose an option:")
        print("1. Create a Numpy Array")
        print("2. Indexing/Slicing and Mathematical Operations 💚")
        print("3. Combine or Split Arrays")
        print("4. Search, Sort, or Filter Arrays")
        print("5. Compute Aggregates and Statistics")
        print("6. Exit")

        choice = int(input("Enter your choice: "))

        match choice:
            case 1:
                print("Array Creation:")
                print("Select the type of array to create:")
                print("1. 1D Array")
                print("2. 2D Array")
                print("3. 3D Array")
                array_choice = int(input("Enter your choice: "))

                if array_choice == 1:
                    size = int(input("Enter the size of the 1D array: "))
                    elements = list(map(int, input(f"Enter {size} elements for the array separated by space: ").split()))
                    array = create_array((size,), elements)

                elif array_choice == 2:
                    rows = int(input("Enter the number of rows: "))
                    cols = int(input("Enter the number of columns: "))
                    elements = list(map(int, input(f"Enter {rows * cols} elements for the array separated by space: ").split()))
                    array = create_array((rows, cols), elements)

                elif array_choice == 3:
                    rows = int(input("Enter the number of rows: "))
                    cols = int(input("Enter the number of columns: "))
                    elements = list(map(int, input(f"Enter {rows * cols} elements for the array separated by space: ").split()))
                    # Create a 3D array with depth 1
                    array = create_array((1, rows, cols), elements)

            case 2:
                print("\nIndexing/Slicing:")
                print("Choose an operation:")
                print("1. Indexing")
                print("2. Slicing")
                print("3. Go Back")
                op_choice = int(input("Enter your choice: "))

                match op_choice:
                    case 1:
                        if array.ndim == 1:
                            index = int(input("Enter index: "))
                            result = indexing(array, index, 0)
                        elif array.ndim == 2:
                            row = int(input("Enter row index: "))
                            col = int(input("Enter column index: "))
                            result = indexing(array, row, col)
                        elif array.ndim == 3:
                            depth = 0  # Since depth is fixed as 1
                            row = int(input("Enter row index: "))
                            col = int(input("Enter column index: "))
                            result = indexing(array, row, col, depth)
                        print(f"Indexed value: {result}")

                    case 2:
                        row_range = list(map(int, input("Enter the row range (start:end): ").split(":")))
                        col_range = list(map(int, input("Enter the column range (start:end): ").split(":")))
                        if array.ndim == 1:
                            result = slicing(array, row_range, col_range)
                        elif array.ndim == 2:
                            result = slicing(array, row_range, col_range)
                        elif array.ndim == 3:
                            depth_range = list(map(int, input("Enter the depth range (start:end): ").split(":")))
                            result = slicing(array, row_range, col_range, depth_range)
                        print(f"Sliced Array:\n{result}")

                    case 3:
                        continue

                print("\nMathematical Operations:")
                print("Choose a mathematical operation:")
                print("1. Addition")
                print("2. Subtraction")
                print("3. Multiplication")
                print("4. Division")
                operation = int(input("Enter your choice: "))

                elements = list(map(int, input(f"Enter the same-size array elements separated by space: ").split()))
                other_array = np.array(elements).reshape(array.shape)

                result = math_operations(array, other_array, operation)
                print(f"Result of Operation:\n{result}")

            case 3:
                print("\nCombine or Split Arrays:")
                print("Choose an option:")
                print("1. Combine Arrays")
                print("2. Split Array")
                sub_choice = int(input("Enter your choice: "))

                match sub_choice:
                    case 1:
                        elements = list(map(int, input("Enter the elements of another array to combine (separated by space): ").split()))
                        other_array = np.array(elements).reshape(array.shape)
                        result = combine_arrays(array, other_array)
                        print(f"Combined Array:\n{result}")

                    case 2:
                        num_splits = int(input("Enter the number of splits: "))
                        result = split_array(array, num_splits)
                        print(f"Split Arrays:\n{result}")

            case 4:
                print("\nSearch, Sort, or Filter Arrays:")
                print("Choose an option:")
                print("1. Search a value")
                print("2. Sort the array")
                print("3. Filter values")
                sub_choice = int(input("Enter your choice: "))

                match sub_choice:
                    case 1:
                        value = int(input("Enter value to search: "))
                        result = search_value(array, value)
                        print(f"Value found at indices: {result}")

                    case 2:
                        result = sort_array(array)
                        print(f"Sorted Array:\n{result}")

                    case 3:
                        condition = int(input("Enter the condition to filter values: "))
                        result = filter_array(array, condition)
                        print(f"Filtered Array:\n{result}")

            case 5:
                print("\nCompute Aggregates and Statistics:")
                print("Choose an aggregate/statistical operation:")
                print("1. Sum")
                print("2. Mean")
                print("3. Median")
                print("4. Standard Deviation")
                print("5. Variance")
                operation = int(input("Enter your choice: "))

                match operation:
                    case 1:
                        print(f"Sum of Array: {sum(array)}")
                    case 2:
                        print(f"Mean of Array: {mean(array)}")
                    case 3:
                        print(f"Median of Array: {median(array)}")
                    case 4:
                        print(f"Standard Deviation of Array: {std_dev(array)}")
                    case 5:
                        print(f"Variance of Array: {variance(array)}")

            case 6:
                print_exit_message()
                break

main()


Welcome to the NumPy Analyzer!

Choose an option:
1. Create a Numpy Array
2. Indexing/Slicing and Mathematical Operations 💚
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
Enter your choice: 1
Array Creation:
Select the type of array to create:
1. 1D Array
2. 2D Array
3. 3D Array
Enter your choice: 2
Enter the number of rows: 2
Enter the number of columns: 3
Enter 6 elements for the array separated by space: 10 20 30 40 50 60
Array created successfully:
[[10 20 30]
 [40 50 60]]

Choose an option:
1. Create a Numpy Array
2. Indexing/Slicing and Mathematical Operations 💚
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
Enter your choice: 2

Indexing/Slicing:
Choose an operation:
1. Indexing
2. Slicing
3. Go Back
Enter your choice: 2
Enter the row range (start:end): 0:2
Enter the column range (start:end): 1:3
Sliced Array:
[[20 30]
 [50 60]]

Mathematical Operations:
Choose a